USE [master]
GO

/****** Object:  Database [ADM]    Script Date: 3/4/2026 11:37:51 PM ******/
CREATE DATABASE [ADM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AMD_Data', FILENAME = N'D:\downloads\SQL2025\MSSQL17.MSSQLSERVER\MSSQL\DATA\ADM_Data.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [FG_Transactions] 
( NAME = N'ADM_Trans', FILENAME = N'D:\downloads\SQL2025\MSSQL17.MSSQLSERVER\MSSQL\DATA\ADM_Trans.ndf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 20480KB )
 LOG ON 
( NAME = N'ADM_Log', FILENAME = N'D:\downloads\SQL2025\MSSQL17.MSSQLSERVER\MSSQL\DATA\ADM_Log.ldf' , SIZE = 51200KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ADM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ADM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ADM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ADM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ADM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ADM] SET ARITHABORT OFF 
GO

ALTER DATABASE [ADM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ADM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ADM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ADM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ADM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ADM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ADM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ADM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ADM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ADM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ADM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ADM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ADM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ADM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ADM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ADM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ADM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ADM] SET RECOVERY FULL 
GO

ALTER DATABASE [ADM] SET  MULTI_USER 
GO

ALTER DATABASE [ADM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ADM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ADM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ADM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ADM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ADM] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [ADM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ADM] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ADM] SET  READ_WRITE 
GO


